In [1]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(15)
df = pd.DataFrame(np.random.randint(30, 100, 100), columns=['점수'])
df

    점수
0   42
1   35
2   30
3   58
4   57
..  ..
95  35
96  89
97  33
98  82
99  78

[100 rows x 1 columns]

In [5]:
bins = [0, 60, 70, 80, 90, 101]
bin_label = list('가양미우수')

In [7]:
df['등급'] = pd.cut(df['점수'], bins, right=False, labels=bin_label)
df

    점수 등급
0   42  가
1   35  가
2   30  가
3   58  가
4   57  가
..  .. ..
95  35  가
96  89  우
97  33  가
98  82  우
99  78  미

[100 rows x 2 columns]

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# 데이터 분할
x_df = df[['점수']] 
y_df = df['등급'] 

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(x_df, y_df, test_size=0.25, random_state=15)

In [ ]:
# 모델 학습 (만능 모델)
dt_clf = DecisionTreeClassifier(random_state=15)
dt_clf.fit(X_train.values, y_train.values.ravel())

In [12]:
# 모델 예측
y_pred = dt_clf.predict(X_test.values)

In [13]:
from sklearn.metrics import accuracy_score

# 정확도 평가
print(accuracy_score(y_test.values.ravel(), y_pred))

1.0

In [14]:
# 모델 예측
label = dt_clf.predict([[75], [90], [81]])
print(label)

['미' '수' '우']